### ISSUE TITLE
A NuGet cases a crash when running on a simulator

### ISSUE THREAD

**Issue by evgenyvalavin** [AdamEssenmacher/GoogleApisForiOSComponents#10]
I'm not exactly sure what happens, because sometimes an app starts crashing, but sometimes it does not.
I noticed a different behaviour between a simulator and physical device when running the app. Seems like running the app on a simulator makes it crash much frequent than on a physical device. Getting more info...

Noticed issues, combined from different debug sessions:
```
error: Failed to load AOT module 'Firebase.Analytics' while running in aot-only mode: doesn't match assembly.

error: Failed to load AOT module 'Firebase.Installations' while running in aot-only mode: doesn't match assembly.
```

**Comment by AdamEssenmacher** [comment]
Can you try adding a dependency on AdamE.Firebase.iOS.Installations as well?

**Comment by evgenyvalavin** [comment]
See no issues after updating everything to 10.24.0
