### ISSUE TITLE
Privacy manifest support

### ISSUE THREAD

**Issue by WanftMoon** [AdamEssenmacher/GoogleApisForiOSComponents#2]
> Hi @AdamEssenmacher was looking for the issues tab on your repo and there is none, so I would like to kindly ask if you plan on updating your bindings to at least 10.22 which is when they introduced the privacy manifest. These are required starting 1st May.
> ![image](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/assets/20956737/49b86ca4-d1f4-4562-8e64-d6d1d3a878d9)

> Thank you @WanftMoon, I've enabled issues and discussions on the fork so we can track and discuss things over there. I do hope to have 10.22 versions published. 10.16 was latest when I last swept through and updated the fork. In the worst case, it's my understanding that we can take direct control over the privacy manifest.

> @AlleSchonWeg yeah that looks like the long file path issue. I don't know if there's anything that can be done about it. Long file paths are a natural part of how XCFrameworks are packed, and Visual Studio just can't handle them. The nugets work on iOS and (last I checked) can work on Windows as long as you dotnet restore from the CLI.

Hey, moving the conversation here.

From what i understood reading Apple docs, third party libraries like firebase need to have their own manifests. Not so sure if just the act of adding the privacy manifest to an app will solve the fact that the firebase library does not have it. Also, i've seen a bunch of the native libraries running and releasing new versions these past few months to meet the deadline.
That makes me think that Apple may do a deep scan (starting 1st may) and check for xcframeworks manifests for new uploads.
also, they named firebase in their list of frameworks that need the privacy policy.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
![Screenshot 2024-04-17 at 15 25 41](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/assets/20956737/15698a78-4a33-47cb-affc-2ce53773bad7)

https://developer.apple.com/support/third-party-SDK-requirements/

![Screenshot 2024-04-17 at 15 29 51](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/assets/20956737/e095d408-75e0-4785-8789-f43a1a8ed1f9)

Whats your take?

**Comment by AdamEssenmacher** [comment]
Thank you @WanftMoon. If the solution is as simple as bumping some versions, this shouldn't be a big problem.

Otherwise... the path ahead might be painful 😬

**Comment by WanftMoon** [comment]
Hey @AdamEssenmacher any news on the 10.22?

**Comment by AdamEssenmacher** [comment]
10.17 was a harder than ideal, but I'm up to 10.18 and working up there.

These AdamE.* packages are going to be incompatible with any other library that depends on Xamarin.Firebase.iOS.Core, including that barcode scanner. They'll need swap the dependency for AdamE.Firebase.iOS.Core.

**Comment by WanftMoon** [comment]
> 10.17 was a harder than ideal, but I'm up to 10.18 and working up there.
> 
> These AdamE.* packages are going to be incompatible with any other library that depends on Xamarin.Firebase.iOS.Core, including that barcode scanner. They'll need swap the dependency for AdamE.Firebase.iOS.Core.

Yeah, i've let them know about your work. In the meanwhile, i'll probably do something similar to ZXing to maui, and do a custom renderer using [AVFoundation scanner capabilities](https://github.com/Redth/ZXing.Net.Maui/blob/main/ZXing.Net.MAUI/Apple/CameraManager.ios.maccatalyst.cs)

**Comment by WanftMoon** [comment]
@AdamEssenmacher 

I think 10.22 may not be enough, it seems that the list frameworks need to also be signed.

![Screenshot 2024-04-27 at 14 46 21](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/assets/20956737/7d1dc280-a64d-44ef-a76d-155ee96486aa)

**Comment by AdamEssenmacher** [comment]
We're up to 10.20. 4 more to go.

**Comment by AdamEssenmacher** [comment]
10.24 packages have been published, which is what we needed I think. Please re-open the issue if you run into troubles related to the privacy manifest requirements.

**Comment by WanftMoon** [comment]
> 10.24 packages have been published, which is what we needed I think. Please re-open the issue if you run into troubles related to the privacy manifest requirements.

Thanks man, you are a beast!!
