### ISSUE TITLE
dyld[10175]: Symbol not found: _OBJC_CLASS_$_GULNetworkInfo

### ISSUE THREAD

**Issue by Immons** [AdamEssenmacher/GoogleApisForiOSComponents#22]
```
dyld[10175]: Symbol not found: _OBJC_CLASS_$_GULNetworkInfo
Referenced from: <7EFCE371-0EAC-3F87-8683-C6B15DDA9669> /Users/immons/Library/Developer/CoreSimulator/Devices/9948F228-BE7E-4732-A5F7-91302C50CE3E/data/Containers/Bundle/Application/1F806E73-1923-4820-BDA8-7029ED7ECAC6/Mobile.Core.app/Frameworks/FirebaseSessions.framework/FirebaseSessions
  Expected in:     <34E0B44E-4E10-3028-9875-DC18A41938E9> /Users/immons/Library/Developer/CoreSimulator/Devices/9948F228-BE7E-4732-A5F7-91302C50CE3E/data/Containers/Bundle/Application/1F806E73-1923-4820-BDA8-7029ED7ECAC6/Mobile.Core.app/Frameworks/GoogleUtilities.framework/GoogleUtilities
```

AdamE.Firebase.iOS.Analytics version: 10.24.0

this one shows in Console output, application crashes immediately on simulator when starting.

**Comment by rezamohamed** [comment]
I had a similar issue with just getting the other Firebase components working, I had to do this to get it working. `dotnet add package AdamE.Firebase.iOS.Installations --version 10.24.0`

**Comment by AdamEssenmacher** [comment]
@Immons does the above help?

**Comment by Immons** [comment]
@AdamEssenmacher no, still crashing immediately

**Comment by AdamEssenmacher** [comment]
Do you have a repro project?

**Comment by eostarEmployee80** [comment]
Any solution to this?

**Comment by filipnavara** [comment]
I tried to create a repro only to find out that in a clean repro project the `Frameworks/GoogleUtilities.framework/GoogleUtilities` file had the missing symbol, so it seems to be some binary file mix-up. Clean build resolved the issue.
