### ISSUE TITLE
Problem with replacements of Firebase packages (migration of Xamarin.iOS native to .Net8 for iOS)

### ISSUE THREAD

**Issue by kverger997** [AdamEssenmacher/GoogleApisForiOSComponents#27]
Hello,

We have migrated our application to .net 8 and are using the nuget Firebase packages (for iOS).
We've replaced our packages with those provided by this repository (Analytics, Installations, Core, Crashlytics) but several errors remain.

We can debug with the simulator, but not on iPhone

Do you have any ideas?

Thanks

---------

adame.firebase.ios.core 10.24.0.1
adame.firebase.ios.installations 10.24.0
adame.firebase.ios.analytics 10.24.0
adame.firebase.ios.crashlytics 10.24.0

---------

Below are the errors encountered:

> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/Library/Caches/XamarinBuildDownload/GAppM-10.24.0/GoogleAppMeasurement-10.24.0/Frameworks/GoogleAppMeasurement.xcframework'. SupportedPlatform: '/Users/<user>/Library/Caches/XamarinBuildDownload/GAppM-10.24.0/GoogleAppMeasurement-10.24.0/Frameworks/GoogleAppMeasurement.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/Library/Caches/XamarinBuildDownload/FAnlytcs-10.24.0/FirebaseAnalytics-10.24.0/Frameworks/FirebaseAnalytics.xcframework'. SupportedPlatform: '/Users/<user>/Library/Caches/XamarinBuildDownload/FAnlytcs-10.24.0/FirebaseAnalytics-10.24.0/Frameworks/FirebaseAnalytics.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseCore.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseCore.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/GTMSessionFetcher.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/GTMSessionFetcher.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/GoogleDataTransport.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/GoogleDataTransport.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FBLPromises.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FBLPromises.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/GoogleUtilities.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/GoogleUtilities.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/nanopb.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/nanopb.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/leveldb.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/leveldb.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseAppCheckInterop.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseAppCheckInterop.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseAuthInterop.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseAuthInterop.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseCoreExtension.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseCoreExtension.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseCoreInternal.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseCoreInternal.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseMessagingInterop.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseMessagingInterop.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseRemoteConfigInterop.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseRemoteConfigInterop.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseSharedSwift.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseSharedSwift.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/Promises.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/Promises.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseSessions.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.core/10.24.0.1/lib/net6.0-ios16.1/Firebase.Core.resources/FirebaseSessions.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.crashlytics/10.24.0/lib/net6.0-ios16.1/Firebase.Crashlytics.resources/FirebaseCrashlytics.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.crashlytics/10.24.0/lib/net6.0-ios16.1/Firebase.Crashlytics.resources/FirebaseCrashlytics.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]
> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside '/Users/<user>/.nuget/packages/adame.firebase.ios.installations/10.24.0/lib/net6.0-ios16.1/Firebase.Installations.resources/FirebaseInstallations.xcframework'. SupportedPlatform: '/Users/<user>/.nuget/packages/adame.firebase.ios.installations/10.24.0/lib/net6.0-ios16.1/Firebase.Installations.resources/FirebaseInstallations.xcframework', SupportedPlatformVariant: 'ios', SupportedArchitectures: 'simulator'. [/Users/<user>/Dev/<file_project>.csproj]

**Comment by jbouche-work** [comment]
Hi, the error this essentialy that one : 
iOS/Xamarin.Shared.targets(146,3): error : No matching framework found inside ...

One important information, if we build in debug, dotnet build with a debug config is ok.
But we have the errors when we build in a release configuration.

We are in .Net8 for iOS.
Is the nugets are compatible with a .NET8 project (net8-ios) ?

In our Azure pipeline we are using that task : 

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish ios'
  inputs:
    command: 'publish'
    projects: $(theCsproj)
    publishWebProjects: false
    arguments: '-c ${{parameters.theReleaseConfig}} /p:Platform=iPhoneOs'    (((=> the iPhoneOs mentionned in the firebase analytics section)))
    zipAfterPublish: false

We used the 10.24.0 but we not see net8.0-..., only net6.0-ios16.1 lib references, is it normal ?

**Comment by kverger997** [comment]
Hello,

The problem has been solved, we just had to remove the ARMv7 architecture.
