### ISSUE TITLE
[QUESTION] Google maps API

### ISSUE THREAD

**Issue by Alex-Dobrynin** [AdamEssenmacher/GoogleApisForiOSComponents#31]
Have you created the Google maps nugets, or we just need to create them by ourselves? 

If second, then what if I create the nugets for google maps api and put the prefix of your name like it is for firebase? like AdamE.Firebase.iOS.ABTesting but for maps AdamE.Google.iOS.Maps to consolidate the full repo namings?

**Comment by katkusmt** [comment]
I'd like to know this too, we want to update our Google.Maps nugget for cloud based styling.

**Comment by Digifais** [comment]
Hello @Alex-Dobrynin and @katkusmt,

We've released the bindings for GoogleMaps v9.1.1 as a NuGet package [here](https://www.nuget.org/packages/AdamE.Google.iOS.Maps). Feedback is appreciated.

**Comment by Alex-Dobrynin** [comment]
@Digifais  Hi, you have done very important thing. Appreciate your work and time
