### ISSUE TITLE
[iOS] Must restart the app at least once to receive push notifications

### ISSUE THREAD

**Issue by Lee31416** [AdamEssenmacher/GoogleApisForiOSComponents#37]
In our project, only on ios we need to restart the app at least once to receive push notifications. After restarting the app once everything works fine. We request permissions and got logs that say they are granted and then we register for push notifications with the apns which also logs success. Then we register the firebase token with our backend that sends the push notifications also returning success. I tried using xamarin.firebase instead of this package and we couldn't receive any push and the fcm was null on first launch. That made me think that both packages for slim bindings on ios might be at fault. We are currently blocked on this since no workaround was found.

**Comment by miroatp** [comment]
I'm not sure whether it's of any help for you but I remember the requirement to start the app without debugger to receive the notifications. It's mentioned [here](https://www.nuget.org/packages/Plugin.Firebase.CloudMessaging) as one of the iOS Specifics.

Do you have the same issue in the test production build downloaded from Testflight?

**Comment by Lee31416** [comment]
The issue was that firebase doesn't map the apns token correctly or it does but too late for our purpose, the fix was to manually set the apns token in the app delegate and wait with a task completion source that the delegate releases after it's done so we can proceed with fetching the fcm token
