### ISSUE TITLE
Couldn't copy issue

### ISSUE THREAD

**Issue by Th3L0x** [AdamEssenmacher/GoogleApisForiOSComponents#55]
Could not copy "C:\N\adame.firebase.ios.core\10.29.0.1\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseSharedSwift.xcframework\ios-arm64_x86_64-simulator\FirebaseSharedSwift.framework\Modules\FirebaseSharedSwift.swiftmodule\arm64-apple-ios-simulator.swiftinterface" to "bin\Release\net8.0-ios\ios-arm64\Firebase.Core.resources\FirebaseSharedSwift.xcframework\ios-arm64_x86_64-simulator\FirebaseSharedSwift.framework\Modules\FirebaseSharedSwift.swiftmodule\arm64-apple-ios-simulator.swiftinterface". Beginning retry 6 in 1000ms. Could not find a part of the path 'bin\Release\net8.0-ios\ios-arm64\Firebase.Core.resources\FirebaseSharedSwift.xcframework\ios-arm64_x86_64-simulator\FirebaseSharedSwift.framework\Modules\FirebaseSharedSwift.swiftmodule\arm64-apple-ios-simulator.swiftinterface'.

Running from visual studio I'm getting this error, from cmd it's wokring.

**Comment by AdamEssenmacher** [comment]
It's the long path issue as documented in the readme.
