### ISSUE TITLE
Firebase Crashlytics NuGet

### ISSUE THREAD

**Issue by evgenyvalavin** [AdamEssenmacher/GoogleApisForiOSComponents#7]
Hi!

The Release Monitoring dashboard of Firebase Crashlytics requires the minimum version of the Crashlytics SDK to be v10.8.0+.
It would be nice to have an updated NuGet with the Crashlytics.

Thank you.

**Comment by AdamEssenmacher** [comment]
@evgenyvalavin I'll include an -alpha version in the next batch of updated bindings if you can help me validate / test them.

**Comment by evgenyvalavin** [comment]
@AdamEssenmacher yes, I'm up to test the nuget and help you.

I'm new to ios bindings. I hope to find some time in the future to dive deep at least a little bit.

**Comment by evgenyvalavin** [comment]
@AdamEssenmacher I've come across an interesting issue trying to build new Firebase NuGets with an old Xamarin one.
For example:
1. If a csproj contains only "AdamE.Firebase.iOS.*" NuGets I can build an .api fine.
2. If a csproj contains  "AdamE.Firebase.iOS.*" and "Xamarin.Firebase.iOS" NuGets the project doesn't build successfully.

`
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error: clang++ exited with code 1: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked framework 'GoogleAppMeasurement' [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : Undefined symbols for architecture arm64: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :   "_APMAnalyticsConfiguration", referenced from: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :       +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics.o) [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :   "_APMAppMeasurementOriginFirebase", referenced from: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :       +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics.o) [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :   "_APMConsentSettings3P", referenced from: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :       +[FIRAnalytics setConsent:] in FirebaseAnalytics(FIRAnalytics.o) [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :   "_APMFormattedEventName", referenced from: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :       +[FIRAnalytics logEventWithOrigin:name:parameters:] in FirebaseAnalytics(FIRAnalytics.o) [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :   "_APMFormattedUserPropertyName", referenced from: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :       +[FIRAnalytics setUserPropertyString:forName:] in FirebaseAnalytics(FIRAnalytics.o) [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :   "_APMIsAnalyticsCollectionDeactivated", referenced from: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :       +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics.o) [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :   "_APMIsAnalyticsCollectionEnabled", referenced from: [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :       +[FIRAna [/Users/runner/work/1/s/src/Mobile/iOS.csproj]
`

**Comment by jhartzel** [comment]
What's up - I'm running into the same issue as @evgenyvalavin. Will be looking into this further today. 
Can also assist with validation & testing once ready.

PS: @AdamEssenmacher You're the man for forking this repo and taking this on. Not all heroes wear capes (unless you do).

**Comment by AdamEssenmacher** [comment]
> If a csproj contains "AdamE.Firebase.iOS.*" and "Xamarin.Firebase.iOS" NuGets the project doesn't build successfully.

Yeah this is always going to be the case.

Anything Xamarin.Firebase.iOS.* has a dependency on Xamarin.Firebase.iOS.Core. Likewise, anything AdamE.Firebase.iOS.* has a dependency on AdamE.Firebase.iOS.Core. Xamarin.Firebase.iOS.Core and AdamE.Firebase.iOS.Core pack the same set of common Firebase/Google native libraries, so they cannot be included in the same project. They're fundamentally incompatible. This means that any other 3rd-party plugins/packages out there (i.e. Plugin.Firebase, Shiny, certain barcode scanners...) that use these dependencies all need to agree on importing these native libraries from a central authority, which used to be Microsoft and is now just some random dude in Ohio >.<

This situation is exactly what I warned about in the[ MAUI thread](https://github.com/dotnet/maui/discussions/20359#discussioncomment-9014313) where Microsoft abandoned these components and pointed us over to that slim binding demo library, where I opened [an issue](https://github.com/Redth/DotNet.Platform.SlimBindings/issues/6) pointing out the same that was (quite rudely) shut down.

**Comment by evgenyvalavin** [comment]
Something is not right with the Crashlytics NuGet. My app crashes in 1-2 seconds after startup as soon as I've added the NuGet. And the thing is I can't make it stop crashing after removing the nuget, cleaning everything and building again... Trying to figure this out...
Full report is in the file
[crashlytics_crash.txt](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/files/15126308/crashlytics_crash.txt)

**Comment by evgenyvalavin** [comment]
#10

**Comment by evgenyvalavin** [comment]
Same with 10.20.0-alpha1
<_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly> is set in the csproj

**Comment by AdamEssenmacher** [comment]
Please try adding a dependency on Installations and see if that helps or not. I got 10.20 Crashlytics to work.

**Comment by evgenyvalavin** [comment]
Updated to 10.24.0. Everything works fine. Thank you @AdamEssenmacher!
