### ISSUE TITLE
Firebase DynamicLinks NuGet

### ISSUE THREAD

**Issue by Object531** [AdamEssenmacher/GoogleApisForiOSComponents#9]
>Hi, @AdamEssenmacher
>You have helped me to see a silver lining on the implementation of the privacy manifest.
>Thanks you too much.
>
>Do you have any plans for Nuget in Firebase.iOS.DynamicLinks?

>@Object531 please open an issue over at the fork to track it. I can work with you to try to get updated bindings for DynamicLinks published.

moving the conversation here.

We appreciate your work to bring these packages up to date.

According to Apple's documentation, FirebaseDynamicLinks is another SDK that requires a privacy manifest.
And this may be added to the checklist for review starting May 1.

https://developer.apple.com/support/third-party-SDK-requirements/
![ss2024-04-25 172519](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/assets/60146654/007632c7-1b12-44d9-92ae-9d98eb163b50)

https://developer.apple.com/news/upcoming-requirements/?id=05012024a
![ss2024-04-25 175632](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/assets/60146654/c6741588-a819-4775-bae5-ae12f2552970)

Looking forward to seeing Nuget's update on FirebaseDynamicLinks.

Thank you again.

**Comment by AdamEssenmacher** [comment]
10.20 includes an -alpha package for DynamicLinks. Test it and and let me know if it's working for you or not!

**Comment by Object531** [comment]
Thank you for releasing the Nuget package version. @AdamEssenmacher 

I have replaced “Xamarin.Firebase.iOS.DynamicLinks” with “AdamE.Firebase.iOS.DynamicLinks”.
https://www.nuget.org/packages/AdamE.Firebase.iOS.DynamicLinks/10.24.0-alpha1

However, it fails with the following error

>/Users///////EXEC: Error: /Applications/Xcode15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: missing argument(s) to: -o option
>
>/Users///.nuget/packages/adame.firebase.ios.core/10.24.0/buildTransitive/AdamE.Firebase.iOS.Core.targets(5,5): Error MSB3073: The command "/Applications/Xcode15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip  -r -o " exited with code 1. (MSB3073) 

NET 8.0 (8.0.201) enabled on my Mac, but this does not happen with my current version of“Xamarin.Firebase.iOS.DynamicLinks”ver 8.10.0.3, and the project builds fine.
https://www.nuget.org/packages/Xamarin.Firebase.iOS.DynamicLinks

On the other hand, some say that this is a problem with “xamarin.GoogleApisForiOSComponents”.
https://github.com/xamarin/GoogleApisForiOSComponents/issues/646

Thank you

**Comment by AdamEssenmacher** [comment]
AdamE.Firebase.iOS.Core 10.24.0.1 has the bitcode stuff removed. Give it a try.
